import type { Metadata } from "next";
import "./globals.css";
import Script from 'next/script'

import React from "react";

export const metadata: Metadata = {
  title: "Capybuk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href='/assets/img/capybuk-logo.png' />
      </head>
      <body className="w-full min-h-[100vh]">
        {children}
        <Script src="https://kit.fontawesome.com/8a3aa853ee.js" strategy="afterInteractive"></Script>
      </body>
    </html>
  );
}
