import type { Metadata } from "next";
import "./globals.css";
import Script from 'next/script'

import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-[100vh]">
        <div className="flex justify-center items-center flex-col w-full min-h-[100vh]">
          {children}
        </div>
        <Script src="https://kit.fontawesome.com/8a3aa853ee.js" strategy="afterInteractive"></Script>
      </body>
    </html>
  );
}
